### ISSUE TITLE
Adding a column after another existing column

### ISSUE THREAD

**Issue by ngrevet** [laravel-doctrine/migrations#40]
Laravel 5.3 exposes [a method to add a column](https://laravel.com/docs/5.3/migrations#column-modifiers) to a table at a precise position (after a given existing column). I think it's missing from this library or did I miss it somewhere?

**Comment by martin-georgiev** [comment]
@ngrevet-lightspeed have in mind that specifying the new column position is not a SQL-wide feature and probably it is better if you avoid using it.

**Comment by ngrevet** [comment]
Sure I know, but still, Laravel has a disclaimer for that, I thought it could work the same way:
> `->after('column')`	Place the column "after" another column (MySQL Only) 

It feels starnge to just dump new fields at the end of tables with no regard for their logical order or grouping. You end up with fucked up schemas.

**Comment by martin-georgiev** [comment]
Maybe there is some confusion here around Doctrine's purpose and how it is intended to work.
Doctrine is built to be as datastore agnostic as sensibly possible. From a data perspective point-of-view, it will not matter if your new column is placed in a particular position or not, as this doesn't affect the data or the server performance. More on that, Doctrine shall isolate your code from the datastore specifics, so you should not care (well... not really) what and how is stored. That's why there was no attempt to implement such functionality in Doctrine in the first place. If you really want to enforce particular order, the best way will be to edit the auto-generated migration and add the necessary native SQL instruction.

**Comment by ngrevet** [comment]
Good point, duly noted.
I understand the idea behind this decision, my OCDs are just kicking in when I look at the table in a SQL client 😀
