### ISSUE TITLE
How to register all migrations from package in the ServiceProvider laravel?

### ISSUE THREAD

**Issue by loperd** [laravel-doctrine/migrations#82]
I have https://github.com/nWidart/laravel-modules this package, and i want to registered all migrations with ServiceProvider. How to make it???

**Comment by SPie** [comment]
As far as I understood, you have to specify a directory for your migrations in the `config/migrations.php` file.
```php
    /*
    |--------------------------------------------------------------------------
    | Migration Directory
    |--------------------------------------------------------------------------
    |
    | This directory is where all migrations will be stored for this entity
    | manager. Use different directories for each entity manager.
    |
    */
    'directory' => database_path('migrations'),
```

**Comment by loperd** [comment]
@SPie i need to register on the fly. I have modules and i need register all migrations in the ModuleServiceProvider. Understand?
I'm sorry for my bad english..

**Comment by SPie** [comment]
@Renay I think it is not possible at the moment because the migration configuration gets the path for the migration from the config file.
You would need to write your own `Doctrine\DBAL\Migrations\Finder\MigrationFinderInterface`. To initialize the `LaravelDoctrine\Migrations\Configuration\Configuration` with your custom `MigrationFinder` you have to write a custom `LaravelDoctrine\Migrations\Naming\NamingStrategy`, where `getFinder()` returns you custom `MigrationFinder`. 
But this would just be a workaround because your custom `MigrationFinder` will still get the migrations directory path from the config file, so you would have to ignore the path and build your own logic to get the migrations from the different modules.
Maybe you can also write your own `LaravelDoctrine\Migrations\Configuration\ConfigurationFactory` to overwrite the part, where the migrations directory path is set to the configuration, so you can get the different migrations how you like.

**Comment by loperd** [comment]
@SPie Okay, thx. I understand :+1:
